"""campaign locate_by

Revision ID: 11165e4f9bfa
Revises: 3cfa485d5665
Create Date: 2015-08-09 21:59:42.109830

"""

# revision identifiers, used by Alembic.
revision = '11165e4f9bfa'
down_revision = '3cfa485d5665'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('locate_by', sa.String(length=100), nullable=True))

    with op.batch_alter_table('campaign_phone', schema=None) as batch_op:
        batch_op.alter_column('call_in_allowed',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_phone', schema=None) as batch_op:
        batch_op.alter_column('call_in_allowed',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    with op.batch_alter_table('campaign_campaign', schema=None) as batch_op:
        batch_op.drop_column('locate_by')

    ### end Alembic commands ###
