"""audiorecording hidden

Revision ID: 125dd1a9bab5
Revises: 2bd538139427
Create Date: 2015-07-13 17:54:56.973214

"""

# revision identifiers, used by Alembic.
revision = '125dd1a9bab5'
down_revision = '2bd538139427'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_recording', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hidden', sa.Boolean(name='hidden_bool'), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_recording', schema=None) as batch_op:
        batch_op.drop_column('hidden')

    ### end Alembic commands ###
