""" CampaignTarget extend db.Model, gains id

Revision ID: 14b18b469695
Revises: 200bbedeb17f
Create Date: 2015-06-11 15:48:07.036289

"""

# revision identifiers, used by Alembic.
revision = '14b18b469695'
down_revision = '200bbedeb17f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_target_sets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_target_sets', schema=None) as batch_op:
        batch_op.drop_column('id')

    ### end Alembic commands ###
