"""add campaign state field

Revision ID: 1701a61ee616
Revises: 3e41f489b894
Create Date: 2015-05-28 16:44:39.230070

"""

# revision identifiers, used by Alembic.
revision = '1701a61ee616'
down_revision = '3e41f489b894'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_state', sa.String(length=100), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_campaign', schema=None) as batch_op:
        batch_op.drop_column('campaign_state')

    ### end Alembic commands ###
