"""add campaign status code

Revision ID: 1a448b3c4526
Revises: 46285fcd5ed
Create Date: 2015-05-28 16:14:22.594862

"""

# revision identifiers, used by Alembic.
revision = '1a448b3c4526'
down_revision = '46285fcd5ed'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status_code', sa.SmallInteger(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_campaign', schema=None) as batch_op:
        batch_op.drop_column('status_code')

    ### end Alembic commands ###
