"""recording_key_unique

Revision ID: 26321c30fe0b
Revises: 32df0b86c09a
Create Date: 2015-07-14 21:54:01.806058

"""

# revision identifiers, used by Alembic.
revision = '26321c30fe0b'
down_revision = '32df0b86c09a'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_recording', schema=None) as batch_op:
        batch_op.drop_constraint(u'uq_campaign_recording_version', type_='unique')
        batch_op.create_unique_constraint(None, ['key', 'version'])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_recording', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(u'uq_campaign_recording_version', ['version'])

    ### end Alembic commands ###
