"""phone number m2m

Revision ID: 2bd538139427
Revises: a1f4cdc4aa
Create Date: 2015-07-10 17:43:05.337612

"""

# revision identifiers, used by Alembic.
revision = '2bd538139427'
down_revision = 'a1f4cdc4aa'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_phone_numbers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False,
                            server_default=sa.schema.DefaultClause("0")))
        # have to specify default here, because column is not nullable
        # but because it's new, there should be no problems with setting ids to 0

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_phone_numbers', schema=None) as batch_op:
        batch_op.drop_column('id')

    ### end Alembic commands ###
