"""Create campaigns table

Revision ID: 2ca033d14a4
Revises: 4eb4c2449a5b
Create Date: 2015-05-06 21:31:37.220940

"""

# revision identifiers, used by Alembic.
revision = '2ca033d14a4'
down_revision = '4eb4c2449a5b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('number', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('campaign_campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('campaign_phone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_target_sets',
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign_campaign.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['campaign_target.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaign_target_sets')
    op.drop_table('campaign_phone')
    op.drop_table('campaign_campaign')
    op.drop_table('campaign_target')
    ### end Alembic commands ###
