"""Create user model
First revision

Revision ID: 3041ee8e1af7
Revises: 
Create Date: 2015-04-30 14:33:51.426728

"""

# revision identifiers, used by Alembic.
revision = '3041ee8e1af7'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('openid', sa.String(length=100), nullable=True),
    sa.Column('activation_key', sa.String(length=100), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.Column('role_code', sa.SmallInteger(), nullable=True),
    sa.Column('status_code', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('openid')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_user')
    ### end Alembic commands ###
