"""segment

Revision ID: 3a64ac078961
Revises: 52ed7015761c
Create Date: 2015-06-05 14:57:44.277857

"""

# revision identifiers, used by Alembic.
revision = '3a64ac078961'
down_revision = '52ed7015761c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('segment_by', sa.String(length=100), nullable=True))
        batch_op.drop_column('target_by')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_by', sa.VARCHAR(length=100), nullable=True))
        batch_op.drop_column('segment_by')

    ### end Alembic commands ###
