"""twilio call in

Revision ID: 3cfa485d5665
Revises: 26321c30fe0b
Create Date: 2015-08-08 13:50:20.247461

"""

# revision identifiers, used by Alembic.
revision = '3cfa485d5665'
down_revision = '26321c30fe0b'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_phone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('call_in_allowed', sa.Boolean(), nullable=False, default=False))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_phone', schema=None) as batch_op:
        batch_op.drop_column('call_in_allowed')

    ### end Alembic commands ###
