"""add campaign fields

Revision ID: 3e41f489b894
Revises: 1a448b3c4526
Create Date: 2015-05-28 16:31:18.295983

"""

# revision identifiers, used by Alembic.
revision = '3e41f489b894'
down_revision = '1a448b3c4526'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('call_maximum', sa.SmallInteger(), nullable=True))
        batch_op.add_column(sa.Column('target_by', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('target_ordering', sa.String(length=100), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_campaign', schema=None) as batch_op:
        batch_op.drop_column('target_ordering')
        batch_op.drop_column('target_by')
        batch_op.drop_column('call_maximum')

    ### end Alembic commands ###
