"""twilio phone number model

Revision ID: 46285fcd5ed
Revises: 57aec183600
Create Date: 2015-05-14 15:57:42.263735

"""

# revision identifiers, used by Alembic.
revision = '46285fcd5ed'
down_revision = '57aec183600'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_phone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20), nullable=True))
        batch_op.add_column(sa.Column('twilio_app', sa.String(length=34), nullable=True))
        batch_op.add_column(sa.Column('twilio_sid', sa.String(length=34), nullable=True))
        batch_op.drop_column('phone')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_phone', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('twilio_sid')
        batch_op.drop_column('twilio_app')
        batch_op.drop_column('number')

    ### end Alembic commands ###
