"""audio recording tts

Revision ID: 4e2dff6833fa
Revises: 1df3d6186aa1
Create Date: 2015-06-24 12:54:16.666790

"""

# revision identifiers, used by Alembic.
revision = '4e2dff6833fa'
down_revision = '1df3d6186aa1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_recording', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_to_speech', sa.Text(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_recording', schema=None) as batch_op:
        batch_op.drop_column('text_to_speech')

    ### end Alembic commands ###
