"""create phonenumber field

Revision ID: 4eb4c2449a5b
Revises: 3041ee8e1af7
Create Date: 2015-05-06 19:08:44.526894

"""

# revision identifiers, used by Alembic.
revision = '4eb4c2449a5b'
down_revision = '3041ee8e1af7'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_user', sa.Column('phone', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_user', 'phone')
    ### end Alembic commands ###
