""" initial table creation commands

Revision ID: 50b6324aa438
Revises: 
Create Date: 2015-06-25 22:09:39.345793

"""

# revision identifiers, used by Alembic.
revision = '50b6324aa438'
down_revision = None
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import flask_store


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_phone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('twilio_sid', sa.String(length=34), nullable=True),
    sa.Column('twilio_app', sa.String(length=34), nullable=True),
    sa.Column('number', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_target',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('number', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('openid', sa.String(length=100), nullable=True),
    sa.Column('activation_key', sa.String(length=100), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('last_accessed', sa.DateTime(), nullable=True),
    sa.Column('phone', sqlalchemy_utils.types.phone_number.PhoneNumberType(length=20), nullable=True),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.Column('role_code', sa.SmallInteger(), nullable=True),
    sa.Column('status_code', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('openid')
    )
    op.create_table('campaign_campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('campaign_type', sa.String(length=100), nullable=True),
    sa.Column('campaign_state', sa.String(length=100), nullable=True),
    sa.Column('campaign_subtype', sa.String(length=100), nullable=True),
    sa.Column('segment_by', sa.String(length=100), nullable=True),
    sa.Column('target_ordering', sa.String(length=100), nullable=True),
    sa.Column('allow_call_in', sa.Boolean(), nullable=True),
    sa.Column('call_maximum', sa.SmallInteger(), nullable=True),
    sa.Column('status_code', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('campaign_recording',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=True),
    sa.Column('file_storage', flask_store.sqla.FlaskStoreType(length=256), nullable=True),
    sa.Column('text_to_speech', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign_campaign.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    
    op.create_table('campaign_target_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign_campaign.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['campaign_target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('calls',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('phone_hash', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('call_id', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=25), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign_campaign.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['campaign_target.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_phone_numbers',
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('phone_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign_campaign.id'], ),
    sa.ForeignKeyConstraint(['phone_id'], ['campaign_phone.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaign_phone_numbers')
    op.drop_table('calls')
    op.drop_table('campaign_target_sets')

    op.drop_table('campaign_recording')
    op.drop_table('campaign_campaign')
    op.drop_table('user_user')
    op.drop_table('campaign_target')
    op.drop_table('campaign_phone')
    ### end Alembic commands ###
