"""remove campaign_phone unique

Revision ID: 5108bec7e545
Revises: 3a64ac078961
Create Date: 2015-06-11 12:57:10.010464

"""

# revision identifiers, used by Alembic.
revision = '5108bec7e545'
down_revision = '3a64ac078961'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
