"""campaign.target_set order

Revision ID: 52ed7015761c
Revises: 1701a61ee616
Create Date: 2015-06-03 15:11:23.871948

"""

# revision identifiers, used by Alembic.
revision = '52ed7015761c'
down_revision = '1701a61ee616'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_target_sets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order', sa.Integer(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_target_sets', schema=None) as batch_op:
        batch_op.drop_column('order')

    ### end Alembic commands ###
