"""campaign embed json field

Revision ID: 55af52b20fb3
Revises: 11165e4f9bfa
Create Date: 2015-09-02 15:10:54.213348

"""

# revision identifiers, used by Alembic.
revision = '55af52b20fb3'
down_revision = '11165e4f9bfa'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('embed', sqlalchemy_utils.types.json.JSONType(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_campaign', schema=None) as batch_op:
        batch_op.drop_column('embed')

    ### end Alembic commands ###
