"""campaign subtype

Revision ID: 57aec183600
Revises: 3d60e57ddd1c
Create Date: 2015-05-07 20:37:17.357495

"""

# revision identifiers, used by Alembic.
revision = '57aec183600'
down_revision = '3d60e57ddd1c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_campaign', schema=None) as batch_op:
        batch_op.drop_column('type')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_campaign', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type', sa.INTEGER(), nullable=True))

    ### end Alembic commands ###
