"""audio recording m2m

Revision ID: a1f4cdc4aa
Revises: 2b78395b3dc1
Create Date: 2015-07-10 17:36:54.134155

"""

# revision identifiers, used by Alembic.
revision = 'a1f4cdc4aa'
down_revision = '2b78395b3dc1'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('campaign_recording', schema=None) as batch_op:
        batch_op.drop_index('only_one_selected_version')
        # batch_op.drop_constraint('fk_campaign_recording_campaign_id', type_='foreignkey')
        # couldn't get this constraint to drop, even with specified metadata.naming_convention
        batch_op.drop_column('selected')
        batch_op.drop_column('campaign_id')

    op.create_table('campaign_audio_recordings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('recording_id', sa.Integer(), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign_campaign.id'], ),
    sa.ForeignKeyConstraint(['recording_id'], ['campaign_recording.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(u'campaign_recording', schema=None) as batch_op:
        batch_op.add_column(sa.Column('campaign_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('selected', sa.BOOLEAN(), nullable=True))
        batch_op.create_foreign_key(None, 'campaign_recording', 'campaign_campaign', ['campaign_id'], ['id'])
        batch_op.create_index('only_one_selected_version', ['campaign_id', 'key', 'selected'], unique=1)

    op.drop_table('campaign_audio_recordings')
    ### end Alembic commands ###
